name: Check Markdown math

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-math:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run GitHub style math checker
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run math checker
        run: |
          python3 .scripts/check_math.py .
